export {default as Navbar} from './Navbar/Navbar'
export {default as InfoSection} from './InfoSection/InfoSection'
export {default as ServeSection} from './ServeSection/ServeSection'
export {default as PricingSection} from './PricingSection/PricingSection'
export {default as TeamSection} from './TeamSection/TeamSection'